website:
  urls: https://www.afrikrea.com/fr/categories/clothing
        https://www.afrikrea.com/fr/categories/clothing?page=2
        https://www.afrikrea.com/fr/categories/clothing?page=3



spring:
  datasource:
    url: jdbc:mysql://google/awesome-tempo-412920:europe-west3:scraper/scraper?useSSL=false&allowPublicKeyRetrieval=true
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

