website:
  urls: https://www.afrikrea.com/fr/categories/clothing

  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/your_database_name  # Replace 'your_database_name' with your actual database name
    username: your_username  # Replace 'your_username' with your MariaDB username
    password: your_password  
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate will automatically create/update tables based on entities
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
