website:
  urls: https://www.afrikrea.com/fr/categories/clothing
        https://www.afrikrea.com/fr/categories/clothing?page=2
        https://www.afrikrea.com/fr/categories/clothing?page=3



spring:
  datasource:
    url: jdbc:mysql://34.172.228.231/scraper
    username: root
    password: scraper-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
