website:
  urls: https://marketplace.anka.africa/en/categories/men-clothing
        https://marketplace.anka.africa/en/categories/men-clothing?page=2
        https://marketplace.anka.africa/en/categories/men-clothing?page=3
 #alte link
        #https://anka.africa/en/categories/men-clothing
        #https://anka.africa/en/categories/men-clothing?page=2

#cloud settings
#spring:
#  datasource:
#    url: jdbc:mysql://34.172.228.231:3306/scraper
#    username: scraper
 #   password: njike2000
  #jpa:
   # properties:
    #  hibernate:
     #   dialect: org.hibernate.dialect.MySQL8Dialect
    #hibernate:
     # ddl-auto: update


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scraper
    username: scraper
    password: njike2000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


