version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraper
      MYSQL_USER: scraper
      MYSQL_PASSWORD: njike2000
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
