# Use the official OpenJDK image as the base image
FROM adoptopenjdk:17-jdk-hotspot

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/your-spring-app.jar /app

# Expose the port that your Spring Boot application runs on
EXPOSE 8080

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "ScraperApplication.jar"]
