apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: gcr.io/sinuous-city-406809/your-spring-app
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - deployment.yaml
